name: Security compliance

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - main
  workflow_dispatch:

permissions: read-all # Declare default permissions as read only.

jobs:
  scorecard:
    permissions:
      security-events: write
      id-token: write
    uses: onebeyond/reusable-workflows/.github/workflows/openssf-scorecard.yml@main
